# -*- coding: utf-8 -*-
"""Festive_Sales_Analysis_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u6tPfETMKHiMNRlFbxHf52ibb5o0PxFT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("Diwali Sales Data.csv", encoding='latin1')
df

df.duplicated().sum()

df = df.drop_duplicates()

df.shape

df.drop(['Status', 'unnamed1'], axis = 1, inplace = True)

df.isnull().sum()

df.dtypes

df['Amount'].median()

df['Amount'].fillna(df['Amount'].median(), inplace = True)

df.isnull().sum()

df.columns

df['User_ID'].value_counts()

df[df['User_ID'] == 1001680]

df.columns

"""# **EXPLORATORY DATA ANALYSIS**"""

import seaborn as sns

"""# **GENDER COMPARISON**




"""

sns.countplot(x = 'Gender', data = df)

ax = sns.countplot(x = 'Gender', data = df)
for bars in ax.containers:
    ax.bar_label(bars)

df.groupby(['Gender'], as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False)

sales_gen = df.groupby(['Gender'], as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False)
sns.barplot(x = 'Gender', y = 'Amount', data = sales_gen)

"""# **AGE GROUP ANALYSIS**"""

sns.countplot(data = df, x = 'Age Group', hue = 'Gender')

ax = sns.countplot(data = df, x = 'Age Group', hue = 'Gender')
for bars in ax.containers:
  ax.bar_label(bars)

df.columns

sales_age = df.groupby(['Age Group'], as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False)
sns.barplot(x = 'Age Group', y = 'Amount', data = sales_age, hue = 'Age Group', palette = 'viridis', legend=False)
plt.show()

plt.figure(figsize=(10, 6))
ax = sns.barplot(x = 'Age Group', y = 'Amount', data = sales_age, hue = 'Age Group', palette='magma', legend=False) # Changed palette to 'magma'
for bars in ax.containers:
    ax.bar_label(bars)
plt.title('Total Sales Amount by Age Group')
plt.xlabel('Age Group')
plt.ylabel('Total Sales Amount')
plt.show()

"""# From above graphs we can say that most of the buyers are of age 26-35 where female are the ones buying the most."""

df.columns

"""# **STATE-WISE ANALYSIS**"""

sales_state = df.groupby('State', as_index = False)['Orders'].sum().sort_values(by = 'Orders', ascending = False)
sales_state

plt.figure(figsize = (25,8))
order_state = df.groupby('State', as_index = False)['Orders'].sum().sort_values(by = 'Orders', ascending = False)
sns.barplot(x = 'State', y = 'Orders', data = order_state, palette = 'viridis')

plt.figure(figsize = (25, 5))
sales_state = df.groupby('State', as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False)
sns.barplot(x = 'State', y = 'Amount', data = sales_state, palette = 'viridis')

"""***From the above graphs we interpret that people from Uttar Pradesh, Maharashtra & Karnataka are buying the most.***"""



"""# **MARITAL STATUS ANALYSIS**"""

df.columns

plt.figure(figsize = (5,5))
sales_marital = df.groupby(['Marital_Status','Gender'], as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False)
sns.barplot(x = 'Marital_Status', y = 'Amount', hue = 'Gender' ,data = sales_marital, palette = 'viridis')

"""# **OCCUPATION**"""

df.columns

plt.figure(figsize = (25, 5))
ax = sns.countplot(x = 'Occupation', data = df, palette = 'viridis')
for bars in ax.containers:
  ax.bar_label(bars)

plt.figure(figsize = (25, 5))
order_occupation = df.groupby('Occupation', as_index = False)['Orders'].sum().sort_values(by = 'Orders', ascending = False)
sns.barplot(x = 'Occupation', y = 'Orders', data = order_occupation, palette = 'viridis')

plt.figure(figsize = (25, 5))
sales_occupation = df.groupby('Occupation', as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False)
sns.barplot(x = 'Occupation', y = 'Amount', data = sales_occupation, palette = 'viridis')

"""**From this we get to know that people who are working in IT sector, Healthcare, Aviation are ordering more.**

# **Product Category**
"""

df.columns

plt.figure(figsize = (25, 5))
ax = sns.countplot(x = 'Product_Category', data = df, palette = 'viridis')
for bars in ax.containers:
  ax.bar_label(bars)

plt.figure(figsize = (25, 5))
sales_product_category = df.groupby('Product_Category', as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False).head(10)
sns.barplot(x = 'Product_Category', y = 'Amount', data = sales_product_category, palette = 'viridis')

"""**From the above graphs we get to know that people are spending most of their income on Food, Clothing & Apparel, Footwear & Shoes, Electronics & Gadgets**

# **CONCLUSION**

***Married women age group 26-35 years from Uttar Pradesh, Maharshtra, Karnataka, working in IT, Healthcare, Aviation are moremlikely to buy products from Food, Clothing & Electronics category.***
"""